# UI Services
---
ui:
    services:
        # analytics: {}
        coreService: {}
        data: {}
        heartbeat: {}
        instrumentation: {}
        ko-component: {}
        notification: {}
        route: {}
        rpc: {}
        schema: {}
        session: {}
        type: {}
        userprofile: {}
        widget: {}
        feeds: {}
        # dynamic-service: {}
        menu:
            menus:
                hamburger:
                    sections:
                        main:
                            items:
                                - id: narrative
                                  auth: true
                                - id: jgi-search
                                  auth: true
                                - id: biochem-search
                                  auth: true
                        developer:
                            items:
                                - id: about-services
                                  auth: true
                                  allowRoles: [DevToken]
                                - id: narrative-info
                                  auth: true
                                  allow: [alpha]
                                - id: dashboard2
                                  auth: true
                                  allow: [alpha]
                                - id: databrowser
                                  auth: true
                                  allow: [alpha]
                                - id: typebrowser
                                  auth: true
                                  allow: [alpha]
                        help:
                            items:
                                - id: about
                                  auth: false
                                - id: contact-kbase
                                  auth: false
                                - id: help
                                  auth: false
                sidebar:
                    sections:
                        main:
                            items:
                                - id: dashboard
                                  auth: true
                                - id: organizations
                                  auth: true
                                - id: public-search
                                  auth: true
                                  allow: [alpha]
                                - id: appcatalog
                                  auth: false
                                - id: search
                                  auth: true
                                - id: jobbrowser
                                  # The label can ovveride the label from the plugin here
                                  label: Jobs
                                  auth: true
                                - id: account
                                  auth: true
                                - id: feeds
                                  auth: true
