## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        narrativemanager
    -
        narrativestore
    # external:
    -
        name: viswidgetdemo
        globalName: kbase-ui-plugin-demo-vis-widget
        cwd: src/plugin
        version: 0.1.1
        source:
            bower: {}
    -
        name: viswidgets
        globalName: kbase-ui-plugin-vis-widgets
        cwd: src/plugin
        version: 0.1.1
        source:
            bower: {}
    -
        name: typeview
        globalName: kbase-ui-plugin-typeview
        version: 0.1.1
        source:
            bower: {}
    -
        name: dataview
        globalName: kbase-ui-plugin-dataview
        version: 0.1.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: dashboard
        globalName: kbase-ui-plugin-dashboard
        version: 0.1.1
        cwd: src/plugin
        source:
            bower: {}
    -
        name: databrowser
        globalName: kbase-ui-plugin-databrowser
        version: 0.1.1
        cwd: src/plugin
        source:
            bower: {}
    -
        name: typebrowser
        globalName: kbase-ui-plugin-typebrowser
        version: 0.1.2
        cwd: src/plugin
        source:
            bower: {}
    -
        name: datawidgets
        globalName: kbase-ui-plugin-datawidgets
        version: 0.1.3
        cwd: src/plugin
        source:
            bower: {}
    #-
    #    globalName: taxon
    #    #bower:
    #    #     globalName: kbase-ui-plugin-taxon
    #    #     version: eapearson/kbase-ui-plugin-taxon#master
    #    directory:
    #        path: kbase-ui-plugin-taxon
    #    copy:
    #        path: src/plugin
    -
        name: dataapidemo
        globalName: kbase-ui-plugin-data-api-demo
        version: 0.1.0
        cwd: src/plugin
        source:
            bower:
                version: eapearson/kbase-ui-plugin-data-api-demo#master
            # directory:
                # This is where to find repos; it will be the level above kbase-ui
                # if not specified, or may be overridden in the dev config.
                # root: /Users/erik/work/kbase/sprints/data-api-widgets
               
# Copy these directories into the modules
# There are two forms, as for plugins. 
# a bower: section will specify a bower dependency
# a copy: section will specify a directory to copy literally into modules
# a link: section will specify a directory to link into modules

modules:
    -
        globalName: kbase-ui-widget
        version: 0.1.4
        source:
            bower: {}
    -
        globalName: kbase-common-js
        version: 0.1.3
        source:
            bower: {}
    -
        globalName: kbase-service-clients-js
        version: 0.1.4
        source:
            bower: {}
    -
        globalName: kbase-data-api-js-clients
        version: 0.1.4
        source:
            bower: {}