# This is used to copy specific files from bower_components to the build.
# It is yucky that we have to do this, but there is no universal bower package
# format, and some bower repos are complete source hairballs. We reduce the code
# side significantly, and eliminate the possibility of serving up hairball files
# from the kbase-ui service.
# TODO: I've learned more about bower conventions since this time -- the main
# property is pretty well supported. Not universally, but better. We only really
# need to list the packages here and create config for exceptions
# TODO: document the format
bowerFiles:
  - name: knockout
    cwd: dist
    src: knockout.js
    bowerComponent: true
  - name: knockout-arraytransforms
    cwd: dist
    src: knockout-arraytransforms.js
    bowerComponent: true
  - name: knockout-projections
    cwd: dist
    src: knockout-projections.js
    bowerComponent: true
  - name: knockout-switch-case
    src: knockout-switch-case.js
    bowerComponent: true
  - name: knockout-validation
    cwd: dist
    src: knockout.validation.js
    bowerComponent: true
  - name: bower-knockout-mapping
    cwd: dist
    src: knockout.mapping.js
    bowerComponent: true
  - name: bootstrap
    cwd: dist
    src:
      - js/bootstrap.js
      - css/bootstrap.css
      - fonts/*
    bowerComponent: true
  - name: eonasdan-bootstrap-datetimepicker
    normalizeDirectory: true
    src:
      - cwd: src/js
        path: bootstrap-datetimepicker.js
      - cwd: build/css
        path: bootstrap-datetimepicker.css
    bowerComponent: true
  - name: font-awesome
    src:
      - css/font-awesome.css
      - fonts/*
    bowerComponent: true
  - name: jquery
    cwd: dist
    bowerComponent: true
  - name: js-yaml
    cwd: dist
    bowerComponent: true
  - dir: pure-uuid
    src:
      - uuid.js
    bowerComponent: true
  - name: require-css
    src:
      - css.js
      - css-builder.js
      - normalize.js
    bowerComponent: true
  - dir: requirejs-yaml
    name: yaml
    bowerComponent: true
  - dir: requirejs
    name: require
    bowerComponent: true
  - dir: requirejs-domready
    name: domReady
    bowerComponent: true
  - dir: requirejs-json
    name: json
    bowerComponent: true
  - dir: requirejs-text
    name: text
    bowerComponent: true
  - dir: spark-md5
    name: spark-md5
    bowerComponent: true
  - name: underscore
    bowerComponent: true
  - name: handlebars
    bowerComponent: true
  - name: marked
    bowerComponent: true
    cwd: lib
  - dir: moment
    src:
      - moment.js
    bowerComponent: true
  - name: kb_common
    dir: kbase-common-js
    cwd: dist/kb_common
    src: "**/*"
    bowerComponent: false
  - name: kb_lib
    dir: kbase-common-es6
    cwd: src
    src: "**/*"
    bowerComponent: false
  - name: kb_ko
    dir: kbase-ko-components-js
    cwd: src
    src: "**/*"
    bowerComponent: false
  - name: kb_knockout
    dir: kbase-knockout-extensions-es6
    cwd: src
    src: "**/*"
    bowerComponent: false
  - name: kb_common_ts
    dir: kbase-common-ts
    cwd: dist
    src: "*.js"
    bowerComponent: false
  - dir: numeral
    src:
      - numeral.js
    bowerComponent: true
