    title: KBase UI
    remote_theme: kbaseIncubator/kbase-github-pages-theme
    search_enabled: false
    aux_links: 
        "KBase UI on Github":
            - "//github.com/kbase/kbase-ui"
        "About KBase":
            - "//kbase.us/about"
    navigation:
        menu:
            - label: Overview